language: java

branches:
  except:
    - gh-pages

jdk:
- openjdk7

before_install:
 - unset _JAVA_OPTIONS 

install:
- echo "<settings><servers><server><id>apache.snapshots.https</id><username>${SOSS_USERNAME}</username><password>${SOSS_PASSWORD}</password></server></servers></settings>" > ${HOME}/.m2/settings.xml
#- cat ${HOME}/.m2/settings.xml

script: if [[ "$TRAVIS_SECURE_ENV_VARS" == "true" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then CMD=deploy; else CMD=install; fi; echo $CMD; mvn -B -Pall $CMD

notifications:
  email:
  on_success: never
  on_failure: change

env:
  global:
  - _JAVA_OPTIONS='-Xmx4096m'
  - secure: "ZSWivIr1Km+EpH7rM4e+GGcDyEdlvkmUhF6nN5z1slDVlN3uL02VQuc8Kh7+5w/vaPVPzCdCLj0cGrW0EoXy+hSntOY52WRAkyFgvLRHX4hjmCfzR7Rdm6wxeyvfBdCDaVwwMYdK6ox5zsRQM1g6Zts2e/KrQt4gz5icWuil9Y0="
  - secure: "hJ1W2jOaypXQzsXHXTpFrRW9sTaciXLomvJnzr4Kr66rqwdZqC8Gi77FEx4P3/5kSv0cmQdbPtuCHzfVTZ5eWRqOGENDapQIRheJUYGvrUGBtdT1/tcKAnMKUvVBeyela/sXEPg9/TtHX+52YuasHKMVGTSun9JYIkcJKas8UAE="

